sudo: required
services:
    - docker

before_install:
    - docker build -t javi/react-test -f ./client/Dockerfile.dev

script:
    - docker run -e CI=true javi/react-test npm test

after_success:
    - docker build -t javi/multi-client ./client
    - docker build -t javi/multi-nginx ./nginx
    - docker build -t javi/multi-server ./sever
    - docker build -t javi/multi-worker ./worker
    
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push javi/multi-client
    - docker push javi/multi-nginx
    - docker push javi/multi-server
    - docker push javi/multi-worker