sudo: required
services:
    - docker

before_install:
    - docker build -t jparrareig/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true jparrareig/react-test npm test

after_success:
    - docker build -t jparrareig/multi-client ./client
    - docker build -t jparrareig/multi-nginx ./nginx
    - docker build -t jparrareig/multi-server ./sever
    - docker build -t jparrareig/multi-worker ./worker
    
    - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_ID" --password-stdin
    #- echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_ID --password-stdin
    #- docker login -u "$DOCKER_ID" -p "$DOCKER_PASSWORD"
    - docker push jparrareig/multi-client
    - docker push jparrareig/multi-nginx
    - docker push jparrareig/multi-server
    - docker push jparrareig/multi-worker